spring.application.name=fulfillx

# Validation messages
spring.messages.basename=ValidationMessages

# Pagination defaults
spring.data.web.pageable.default-page-size=20
spring.data.web.pageable.max-page-size=100
spring.data.web.pageable.one-indexed-parameters=false

# OpenAPI / Swagger
springdoc.api-docs.path=/api/v1/docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

# Logging
logging.level.com.aryan.fulfillx=INFO
logging.level.org.springframework.web=WARN
